import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";
import coffeeStoresData from "../data/coffee-store.json";

export async function getStaticProps(context) {
  return {
    props: { coffeeStores: coffeeStoresData },
  };
}

export default function Home({coffeeStores}) {
  const [bannerBtnText, setBannerBtnText] = useState("View stores nearby");
  const handleOnBannerBtnClick = () => {
    setBannerBtnText("Loading..");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoiseseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={bannerBtnText}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Hero img"
            width={700}
            height={400}
            priority
          />
        </div>
        {coffeeStores.length > 0 ? (
          <section className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.name}
                  name={coffeeStore.name}
                  href={`/coffee-store/${coffeeStore.name
                    .toLowerCase()
                    .replace(/ /g, "-")}`}
                  imageUrl={coffeeStore.imgUrl}
                  className={`styles.card`}
                />
              ))}
            </div>
          </section>
        ) : (
          <div></div>
        )}
      </main>
    </div>
  );
}
